src/app/api/getDelegations.ts
src/app/components/Connect/ConnectSmall.tsx
src/app/components/Delegations/Delegation.tsx
src/app/components/Delegations/Delegations.tsx
src/utils/local_storage/toLocalStorageDelegation.ts
src/utils/local_storage/toLocalStorageIntermediateDelegation.ts

If the delegation has overflow, it will be shown inside the ui:
- mobile https://i.imgur.com/hXEoHQ6.png
- desktop https://i.imgur.com/QeTYwHd.png

feature: Overflow UI

---

docs/WalletIntegration.md
src/app/components/Delegations/Delegations.tsx
src/app/components/Stats/Stats.tsx
src/app/page.tsx
src/utils/wallet/okx_wallet.ts
src/utils/wallet/wallet_provider.ts

- Update the signPsbt methods, making sure the method only sign Psbt.
- Updated the doc for the missing new method getBTCTipHeight

fix: signPsbt shall return signed Psbt

---

src/app/components/TestingInfo/TestingInfo.tsx

Text changes https://i.imgur.com/QlS2d3F.png https://i.imgur.com/IJqlVqL.png

feature: Testing app banner

---

src/app/components/Footer/Footer.tsx

feature: Footer flex wrap

---

src/app/components/FinalityProviders/FinalityProviders.tsx
src/app/components/Stakers/Stakers.tsx
src/app/components/Stats/Stats.tsx

Shows proper text for the delegations tooltip https://i.imgur.com/u3MxHNz.png

feature: Delegations tooltip

---

src/app/components/Delegations/Delegation.tsx

Makes delegation status be flat and action button (unbond/withdraw) to have a border
https://i.imgur.com/zpwrXHq.png

feature: Delegation status flat, action button border

---

src/utils/wallet/okx_wallet.ts

Rolls back to signPsbts 
Closes #39

feature: Sign PSBTs

---

src/app/api/getGlobalParams.ts
src/app/components/Connect/ConnectSmall.tsx
src/app/components/Delegations/Delegation.tsx
src/app/components/Delegations/Delegations.tsx
src/app/components/FinalityProviders/FinalityProvider.tsx
src/app/components/FinalityProviders/FinalityProviders.tsx
src/app/components/Header/Header.tsx
src/app/components/Modals/PreviewModal.tsx
src/app/components/Stakers/Staker.tsx
src/app/components/Stakers/Stakers.tsx
src/app/components/StakersFinalityProviders/StakersFinalityProviders.tsx
src/app/components/Staking/FinalityProvider.tsx
src/app/components/Staking/Staking.tsx
src/app/components/Stats/Stats.tsx
src/app/components/Summary/Summary.tsx
src/app/page.tsx
src/utils/btcConversions.ts
src/utils/signForm.ts

Resolves #77 
Tested staking and creating unbonding (without actually seeing unbonded)

feat: Always work with satoshis internally and util conversions

---

package-lock.json
package.json

Solves warning https://nextjs.org/docs/messages/sharp-missing-in-production

feature: NPM sharp

---

src/app/components/Staking/FinalityProviders/FinalityProviders.tsx

Select a BTC finality provider or create your own -> Select a finality provider or create your own

feature: Select fp text change

---

src/app/components/Delegations/Delegation.tsx
src/app/components/Delegations/Delegations.tsx

Center aligned 2 delegations columns on desktop https://i.imgur.com/jvnG7C0.png (tx hash and status)

feature: Center align delegations on desktop

---

src/app/components/Staking/FinalityProviders/FinalityProvider.tsx
src/app/components/Staking/FinalityProviders/FinalityProviders.tsx
tailwind.config.ts

Before: https://i.imgur.com/loKb4NG.png
After: https://i.imgur.com/YC6ElWi.png

feature: Fix finality providers mobile looks

---

src/app/components/Delegations/Delegation.tsx

`isOverflow && status = "Active"` -> status and tooltip is overflow, otherwise show the real status

feature: Overflow state and tooltip is shown on active

---

src/app/common/constants.ts
src/app/components/Delegations/Delegations.tsx
src/app/components/Staking/Form/StakingAmount.tsx
src/app/components/Staking/Form/StakingTime.tsx
src/app/components/Staking/Staking.tsx
src/app/page.tsx

https://github.com/babylonchain/simple-staking/assets/154598612/96dfb2b2-5062-4017-a106-5aab7c9574e4
@jeremy-babylonchain could u help with the UX side to make the text a bit more aligned with the style? i.e the padding/margin etc

feat: show overflow warning when getting close to the cap

---

src/app/components/Staking/Form/StakingAmount.tsx

chore: show both min and max in the staking form

---

src/app/components/Delegations/Delegations.tsx

- was: https://i.imgur.com/EhF7ZaJ.png
- now: https://i.imgur.com/lXGyyRO.png

feature: Misaligned staking history

---

src/app/components/Modals/UnbondWithdrawModal.tsx

chore: update the unbonding text

---

src/app/components/Modals/ConnectModal.tsx
src/utils/wallet/list.ts

- Adds support for QR wallets (`isQRWallet` boolean field)
- Shows a tooltip on them
- Provides an external link documentation https://i.imgur.com/s1Zf4mv.png

feature: QR wallets support

---

package-lock.json

updates package.lock using all the latest `package.json` additions

chore: Update package.lock

---

src/app/components/Delegations/Delegations.tsx
src/app/components/Staking/Staking.tsx
src/app/page.tsx
src/utils/globalParams.ts

return firstActivationHeight from getCurrentGlobalParamsVersion so it shows the height before the activation block

fix first activation height

---

docs/WalletIntegration.md
package-lock.json
package.json
src/app/common/constants.ts
src/app/components/Delegations/Delegation.tsx
src/app/components/Delegations/Delegations.tsx
src/app/components/Staking/Staking.tsx
src/app/page.tsx
src/utils/mempool_api.ts
src/utils/signForm.ts
src/utils/wallet/providers/bitget_wallet.ts
src/utils/wallet/providers/keystone/index.ts
src/utils/wallet/providers/onekey_wallet.ts
src/utils/wallet/providers/tomo_wallet.ts
src/utils/wallet/wallet_provider.ts

Pending merge of this PR https://github.com/babylonchain/btc-staking-ts/pull/24 then we can bump the ts lib version here
But the implementation needed in this repo is pretty much ready for review

Adopt dynamic calculated fees

---

src/app/components/Delegations/Delegation.tsx
src/app/components/Delegations/Delegations.tsx
src/app/components/FAQ/Section.tsx
src/app/components/FAQ/data/questions.ts
src/app/components/FinalityProviders/FinalityProvider.tsx
src/app/components/FinalityProviders/FinalityProviders.tsx
src/app/components/Modals/ConnectModal.tsx
src/app/components/Staking/FinalityProviders/FinalityProvider.tsx
src/app/components/Staking/FinalityProviders/FinalityProviders.tsx

add faq content

---

src/app/components/Staking/Form/StakingTime.tsx

chore: update the staking term wordings

---

src/app/components/Footer/Footer.tsx
src/app/components/Staking/FinalityProviders/FinalityProviders.tsx
src/app/components/Staking/Staking.tsx

fix: fix typo and displaying sBTC instead of BTC

---

src/app/components/Modals/GeneralModal.tsx

Add min width for modals

---

src/app/components/Delegations/Delegation.tsx
src/app/components/Delegations/Delegations.tsx

Current look issue: https://i.imgur.com/89WCLUS.png
This PR:
Desktop mode https://i.imgur.com/VIsAVJa.png
Mobile mode https://i.imgur.com/tBa4poI.png
Some extra small phone https://i.imgur.com/Izig7yJ.png

fix: Delegation overflow mobile fix

---

package-lock.json
package.json

Fix the responsive issue of modal related to Keystone

fix: fix the responsive issue of keystone modal

---

src/app/components/Staking/FinalityProviders/FinalityProvider.tsx

update fp aligment

---

src/app/components/Modals/PreviewModal.tsx
src/app/components/Modals/UnbondWithdrawModal.tsx
src/app/components/Staking/Form/StakingTime.tsx
src/utils/blocksToDisplayTime.ts
src/utils/getState.ts
tests/utils/blocksToDisplayTime.test.ts

Hotfix - Error handling of the unbonding & withdraw request failure

---

src/app/components/Stats/Stats.tsx

add tooltips on negative pending stake

---

tests/helper/index.ts
tests/utils/delegations/signUnbondingTx.test.ts
tests/utils/signPsbtTransaction.test.ts

chores: add unit test for sign psbt transaction 

---

package.json
src/app/page.tsx

resolve useEffects warning

---

package.json
src/app/page.tsx

hotfix - improve err msg for unsupported legacy address

---

package.json
src/app/components/Connect/ConnectSmall.tsx
src/app/components/Connect/ConnectedSmall.tsx
src/app/components/Header/Header.tsx
src/app/components/NetworkBadge/NetworkBadge.tsx
src/app/page.tsx

hotfix - 337 navbar balance and address fix

---

package-lock.json
package.json
src/app/components/Modals/PreviewModal.tsx
src/app/components/Staking/Staking.tsx

chore: Add message about pending delegations on staking modal

---

package.json
src/app/components/Header/Header.tsx

#383
https://github.com/user-attachments/assets/7ae2adfd-4dda-4e2f-a117-4e9a6d115e68

fix balance view
